### ISSUE TITLE
Hi there! Can we add English README?

### ISSUE THREAD

**Issue by Aruelius** [TextAliveJp/textalive-app-basic#1]

**Comment by arcatdmz** [comment]
@Aruelius Your help (pull request) is much appreciated!

**Comment by arcatdmz** [comment]
I've managed to create a pull request to solve this issue.

**Comment by arcatdmz** [comment]
Let me manually re-open the issue so that @Aruelius could close it once s/he confirms the issue gets resolved.

**Comment by Aruelius** [comment]
@arcatdmz Thank you very much!!!
